export const caseTypes: string[] = [
  'ACT8GW - ACT VIII CASE (GUARDIAN & WARDS)',
  'Ca - Civil Appeal',
  'Cc - Estate Acquisition Appeal',
  'Ce - Civil Execution',
  'Cm - Criminal Misc.',
  'Cm - Civil Misc',
  'COMEX - COMMERCIAL EXECUTION',
  'CR - CIVIL REVISION',
  'CS - COMMERCIAL SUIT',
  'Ea - Electricity Act',
  'EJEX - EJECTMENT EXECUTION',
  'EJS - EJECTMENT SUIT',
  'Execution',
  'Gr - GR Case',
  'Ham - Hindu Adoption and Maintenance Case',
  'IC - INSOLVENCY CASE',
  'LA - LETTER OF ADMINISTRATION',
  'Lac - Land Acquisition Cases',
  'Lae - Land Acquisition Execution',
  'LC - LUNACY CASE',
  'Ma - Money Appeal',
  'MA - MISC APPEAL',
  'MACC',
  'MACCEX - MACC EXECUTION',
  'Mc - Misc Case (Pre-emption)',
  'Mcc - Misc. Criminal Case',
  'Mcr - Misc. Criminal Revision',
  'Mec - Misc Execution Case',
  'MEX - MONEY EXECUTION',
  'MISCCASE - MISCELLANEOUS CASE',
  'MJCA - MISC JUDICIAL CASE (ADOPTION)',
  'MS - MONEY SUIT',
  'Msdmc - Matrimonial Suit Divorce Mutual Consent',
  'MTS - MATRIMONIAL SUIT',
  'Mvc Case - Motor Vehicle Case',
  'Oa - Other Appeal',
  'OC - OTHER CASE',
  'Os - Other Suit',
  'PC - PROBATE CASE',
  'RC - REVOCATION CASE',
  'Sc - Sessions Case',
  'Sccs - SCC Suit',
  'SUCC - SUCCESSION CASE (ACT XXXIX CASE)',
  'TA - TITLE APPEAL',
  'TEX - TITLE EXECUTION',
  'Ts - Trust Suit',
  'TS - TITLE SUIT',
];
