export const caseData = [
  {
    caseNo: '2024/001',
    caseType: 'Criminal',
    petitioner: {
      name: 'John Doe',
      address: '123 Main St, Kolkata, India',
    },
    respondent: {
      name: 'Jane Smith',
      address: '456 Market St, Kolkata, India',
    },
    nextDate: '2024-10-15',
    status: 'Pending',
  },
  {
    caseNo: '2024/002',
    caseType: 'Civil',
    petitioner: {
      name: 'Alice Cooper',
      address: '789 Elm St, Delhi, India',
    },
    respondent: {
      name: 'Bob Marley',
      address: '101 High St, Delhi, India',
    },
    nextDate: '2024-09-28',
    status: 'Hearing Scheduled',
  },
  {
    caseNo: '2024/003',
    caseType: 'Family',
    petitioner: {
      name: 'Mary Jane',
      address: '15 Rose Ave, Bangalore, India',
    },
    respondent: {
      name: 'Peter Parker',
      address: '22 Green St, Bangalore, India',
    },
    nextDate: '2024-10-02',
    status: 'Under Review',
  },
  {
    caseNo: '2024/004',
    caseType: 'Labor',
    petitioner: {
      name: 'Carlos Santana',
      address: '89 Orchard Rd, Mumbai, India',
    },
    respondent: {
      name: 'MegaCorp Industries',
      address: '500 Business Park, Mumbai, India',
    },
    nextDate: '2024-09-20',
    status: 'Judgment Reserved',
  },
  {
    caseNo: '2024/005',
    caseType: 'Tax',
    petitioner: {
      name: 'Harvey Specter',
      address: '20 Suits St, Gurgaon, India',
    },
    respondent: {
      name: 'Indian Revenue Service',
      address: 'Govt Building, Gurgaon, India',
    },
    nextDate: '2024-11-10',
    status: 'Filed',
  },
];

export default caseData;

export const clients = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    gender: 'Male',
    mobile: '+91-9876543210',
    alternateMobile: '+91-9876543211',
    address: '123 Park Avenue',
    country: 'India',
    state: 'Maharashtra',
    city: 'Mumbai',
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    gender: 'Female',
    mobile: '+91-9876543212',
    alternateMobile: '+91-9876543213',
    address: '456 Green Street',
    country: 'India',
    state: 'Karnataka',
    city: 'Bangalore',
  },
  {
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    gender: 'Female',
    mobile: '+91-9876543214',
    alternateMobile: '+91-9876543215',
    address: '789 Oak Avenue',
    country: 'India',
    state: 'West Bengal',
    city: 'Kolkata',
  },
  {
    name: 'Robert Brown',
    email: 'robert.brown@example.com',
    gender: 'Male',
    mobile: '+91-9876543216',
    alternateMobile: '+91-9876543217',
    address: '101 Pine Street',
    country: 'India',
    state: 'Delhi',
    city: 'New Delhi',
  },
  {
    name: 'Sophia Williams',
    email: 'sophia.williams@example.com',
    gender: 'Female',
    mobile: '+91-9876543218',
    alternateMobile: '+91-9876543219',
    address: '202 Birch Avenue',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Chennai',
  },
  {
    name: 'Liam Davis',
    email: 'liam.davis@example.com',
    gender: 'Male',
    mobile: '+91-9876543220',
    alternateMobile: '+91-9876543221',
    address: '303 Maple Drive',
    country: 'India',
    state: 'Gujarat',
    city: 'Ahmedabad',
  },
  {
    name: 'Emily Taylor',
    email: 'emily.taylor@example.com',
    gender: 'Female',
    mobile: '+91-9876543222',
    alternateMobile: '+91-9876543223',
    address: '404 Cedar Street',
    country: 'India',
    state: 'Punjab',
    city: 'Amritsar',
  },
  {
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    gender: 'Male',
    mobile: '+91-9876543224',
    alternateMobile: '+91-9876543225',
    address: '505 Spruce Boulevard',
    country: 'India',
    state: 'Uttar Pradesh',
    city: 'Lucknow',
  },
  {
    name: 'Isabella Martin',
    email: 'isabella.martin@example.com',
    gender: 'Female',
    mobile: '+91-9876543226',
    alternateMobile: '+91-9876543227',
    address: '606 Elm Court',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
  },
  {
    name: 'Ethan Lee',
    email: 'ethan.lee@example.com',
    gender: 'Male',
    mobile: '+91-9876543228',
    alternateMobile: '+91-9876543229',
    address: '707 Willow Lane',
    country: 'India',
    state: 'Madhya Pradesh',
    city: 'Bhopal',
  },
];

// types/caseData.ts
export const cases = [
  {
    caseNo: 'C12345',
    courtDetails: 'Supreme Court of India',
    petitioner: 'John Doe',
    respondent: 'Jane Smith',
    nextDate: '2024-09-20',
    status: 'Active',
  },
  {
    caseNo: 'C67890',
    courtDetails: 'High Court of Delhi',
    petitioner: 'Alice Cooper',
    respondent: 'Bob Marley',
    nextDate: '2024-09-30',
    status: 'Closed',
  },
  {
    caseNo: 'C11223',
    courtDetails: 'District Court, Mumbai',
    petitioner: 'Charlie Chaplin',
    respondent: 'Adolf Hitler',
    nextDate: '2024-10-10',
    status: 'Pending',
  },
  // Add more cases as needed
];
